// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package transaction is a generated GoMock package.
package transaction

import (
	context "context"
	reflect "reflect"

	csv "github.com/ferdianexe/simple-statement-reconciliation/internal/repository/csv"
	gomock "github.com/golang/mock/gomock"
)

// MockresourceProvider is a mock of resourceProvider interface.
type MockresourceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockresourceProviderMockRecorder
}

// MockresourceProviderMockRecorder is the mock recorder for MockresourceProvider.
type MockresourceProviderMockRecorder struct {
	mock *MockresourceProvider
}

// NewMockresourceProvider creates a new mock instance.
func NewMockresourceProvider(ctrl *gomock.Controller) *MockresourceProvider {
	mock := &MockresourceProvider{ctrl: ctrl}
	mock.recorder = &MockresourceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresourceProvider) EXPECT() *MockresourceProviderMockRecorder {
	return m.recorder
}

// ParseSystemTransactions mocks base method.
func (m *MockresourceProvider) ParseSystemTransactions(ctx context.Context, path string) ([]csv.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseSystemTransactions", ctx, path)
	ret0, _ := ret[0].([]csv.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseSystemTransactions indicates an expected call of ParseSystemTransactions.
func (mr *MockresourceProviderMockRecorder) ParseSystemTransactions(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseSystemTransactions", reflect.TypeOf((*MockresourceProvider)(nil).ParseSystemTransactions), ctx, path)
}
