// Code generated by MockGen. DO NOT EDIT.
// Source: resource.go

// Package transaction is a generated GoMock package.
package transaction

import (
	context "context"
	reflect "reflect"

	csv "github.com/ferdianexe/simple-statement-reconciliation/internal/repository/csv"
	gomock "github.com/golang/mock/gomock"
)

// MockcsvRepoProvider is a mock of csvRepoProvider interface.
type MockcsvRepoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockcsvRepoProviderMockRecorder
}

// MockcsvRepoProviderMockRecorder is the mock recorder for MockcsvRepoProvider.
type MockcsvRepoProviderMockRecorder struct {
	mock *MockcsvRepoProvider
}

// NewMockcsvRepoProvider creates a new mock instance.
func NewMockcsvRepoProvider(ctrl *gomock.Controller) *MockcsvRepoProvider {
	mock := &MockcsvRepoProvider{ctrl: ctrl}
	mock.recorder = &MockcsvRepoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcsvRepoProvider) EXPECT() *MockcsvRepoProviderMockRecorder {
	return m.recorder
}

// ParseSystemTransactions mocks base method.
func (m *MockcsvRepoProvider) ParseSystemTransactions(ctx context.Context, path string) ([]csv.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseSystemTransactions", ctx, path)
	ret0, _ := ret[0].([]csv.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseSystemTransactions indicates an expected call of ParseSystemTransactions.
func (mr *MockcsvRepoProviderMockRecorder) ParseSystemTransactions(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseSystemTransactions", reflect.TypeOf((*MockcsvRepoProvider)(nil).ParseSystemTransactions), ctx, path)
}
