// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package http is a generated GoMock package.
package http

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockreconcileHandler is a mock of reconcileHandler interface.
type MockreconcileHandler struct {
	ctrl     *gomock.Controller
	recorder *MockreconcileHandlerMockRecorder
}

// MockreconcileHandlerMockRecorder is the mock recorder for MockreconcileHandler.
type MockreconcileHandlerMockRecorder struct {
	mock *MockreconcileHandler
}

// NewMockreconcileHandler creates a new mock instance.
func NewMockreconcileHandler(ctrl *gomock.Controller) *MockreconcileHandler {
	mock := &MockreconcileHandler{ctrl: ctrl}
	mock.recorder = &MockreconcileHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreconcileHandler) EXPECT() *MockreconcileHandlerMockRecorder {
	return m.recorder
}

// HandleReconcile mocks base method.
func (m *MockreconcileHandler) HandleReconcile(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleReconcile", w, r)
}

// HandleReconcile indicates an expected call of HandleReconcile.
func (mr *MockreconcileHandlerMockRecorder) HandleReconcile(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleReconcile", reflect.TypeOf((*MockreconcileHandler)(nil).HandleReconcile), w, r)
}
