// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package csv is a generated GoMock package.
package csv

import (
	csv "encoding/csv"
	io "io"
	reflect "reflect"
	time "time"

	gocsv "github.com/ferdianexe/simple-statement-reconciliation/internal/infrastructure/gocsv"
	gomock "github.com/golang/mock/gomock"
)

// MockinfraProvider is a mock of infraProvider interface.
type MockinfraProvider struct {
	ctrl     *gomock.Controller
	recorder *MockinfraProviderMockRecorder
}

// MockinfraProviderMockRecorder is the mock recorder for MockinfraProvider.
type MockinfraProviderMockRecorder struct {
	mock *MockinfraProvider
}

// NewMockinfraProvider creates a new mock instance.
func NewMockinfraProvider(ctrl *gomock.Controller) *MockinfraProvider {
	mock := &MockinfraProvider{ctrl: ctrl}
	mock.recorder = &MockinfraProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinfraProvider) EXPECT() *MockinfraProviderMockRecorder {
	return m.recorder
}

// CsvNewReader mocks base method.
func (m *MockinfraProvider) CsvNewReader(r io.Reader) *csv.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CsvNewReader", r)
	ret0, _ := ret[0].(*csv.Reader)
	return ret0
}

// CsvNewReader indicates an expected call of CsvNewReader.
func (mr *MockinfraProviderMockRecorder) CsvNewReader(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CsvNewReader", reflect.TypeOf((*MockinfraProvider)(nil).CsvNewReader), r)
}

// CsvReadAll mocks base method.
func (m *MockinfraProvider) CsvReadAll(r gocsv.Reader) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CsvReadAll", r)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CsvReadAll indicates an expected call of CsvReadAll.
func (mr *MockinfraProviderMockRecorder) CsvReadAll(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CsvReadAll", reflect.TypeOf((*MockinfraProvider)(nil).CsvReadAll), r)
}

// TimeInRange mocks base method.
func (m *MockinfraProvider) TimeInRange(d, start, end time.Time) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeInRange", d, start, end)
	ret0, _ := ret[0].(bool)
	return ret0
}

// TimeInRange indicates an expected call of TimeInRange.
func (mr *MockinfraProviderMockRecorder) TimeInRange(d, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeInRange", reflect.TypeOf((*MockinfraProvider)(nil).TimeInRange), d, start, end)
}

// TimeTruncateToDay mocks base method.
func (m *MockinfraProvider) TimeTruncateToDay(t time.Time) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeTruncateToDay", t)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// TimeTruncateToDay indicates an expected call of TimeTruncateToDay.
func (mr *MockinfraProviderMockRecorder) TimeTruncateToDay(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeTruncateToDay", reflect.TypeOf((*MockinfraProvider)(nil).TimeTruncateToDay), t)
}
