// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package reconcile is a generated GoMock package.
package reconcile

import (
	context "context"
	reflect "reflect"

	bank "github.com/ferdianexe/simple-statement-reconciliation/internal/service/bank"
	transaction "github.com/ferdianexe/simple-statement-reconciliation/internal/service/transaction"
	gomock "github.com/golang/mock/gomock"
)

// MockbankServiceManager is a mock of bankServiceManager interface.
type MockbankServiceManager struct {
	ctrl     *gomock.Controller
	recorder *MockbankServiceManagerMockRecorder
}

// MockbankServiceManagerMockRecorder is the mock recorder for MockbankServiceManager.
type MockbankServiceManagerMockRecorder struct {
	mock *MockbankServiceManager
}

// NewMockbankServiceManager creates a new mock instance.
func NewMockbankServiceManager(ctrl *gomock.Controller) *MockbankServiceManager {
	mock := &MockbankServiceManager{ctrl: ctrl}
	mock.recorder = &MockbankServiceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbankServiceManager) EXPECT() *MockbankServiceManagerMockRecorder {
	return m.recorder
}

// GetBankStatementHistory mocks base method.
func (m *MockbankServiceManager) GetBankStatementHistory(ctx context.Context, request []bank.BankStatementParams) ([]bank.BankStatement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankStatementHistory", ctx, request)
	ret0, _ := ret[0].([]bank.BankStatement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankStatementHistory indicates an expected call of GetBankStatementHistory.
func (mr *MockbankServiceManagerMockRecorder) GetBankStatementHistory(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankStatementHistory", reflect.TypeOf((*MockbankServiceManager)(nil).GetBankStatementHistory), ctx, request)
}

// MocktransactionServiceManager is a mock of transactionServiceManager interface.
type MocktransactionServiceManager struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionServiceManagerMockRecorder
}

// MocktransactionServiceManagerMockRecorder is the mock recorder for MocktransactionServiceManager.
type MocktransactionServiceManagerMockRecorder struct {
	mock *MocktransactionServiceManager
}

// NewMocktransactionServiceManager creates a new mock instance.
func NewMocktransactionServiceManager(ctrl *gomock.Controller) *MocktransactionServiceManager {
	mock := &MocktransactionServiceManager{ctrl: ctrl}
	mock.recorder = &MocktransactionServiceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionServiceManager) EXPECT() *MocktransactionServiceManagerMockRecorder {
	return m.recorder
}

// GetUserTransactionHistory mocks base method.
func (m *MocktransactionServiceManager) GetUserTransactionHistory(ctx context.Context, request transaction.TransactionHistoryParams) ([]transaction.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTransactionHistory", ctx, request)
	ret0, _ := ret[0].([]transaction.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTransactionHistory indicates an expected call of GetUserTransactionHistory.
func (mr *MocktransactionServiceManagerMockRecorder) GetUserTransactionHistory(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTransactionHistory", reflect.TypeOf((*MocktransactionServiceManager)(nil).GetUserTransactionHistory), ctx, request)
}
