// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package reconcile is a generated GoMock package.
package reconcile

import (
	context "context"
	csv "encoding/csv"
	io "io"
	reflect "reflect"
	time "time"

	gocsv "github.com/ferdianexe/simple-statement-reconciliation/internal/infrastructure/gocsv"
	reconcile "github.com/ferdianexe/simple-statement-reconciliation/internal/usecase/reconcile"
	gomock "github.com/golang/mock/gomock"
)

// MockreconcileUsecaseManager is a mock of reconcileUsecaseManager interface.
type MockreconcileUsecaseManager struct {
	ctrl     *gomock.Controller
	recorder *MockreconcileUsecaseManagerMockRecorder
}

// MockreconcileUsecaseManagerMockRecorder is the mock recorder for MockreconcileUsecaseManager.
type MockreconcileUsecaseManagerMockRecorder struct {
	mock *MockreconcileUsecaseManager
}

// NewMockreconcileUsecaseManager creates a new mock instance.
func NewMockreconcileUsecaseManager(ctrl *gomock.Controller) *MockreconcileUsecaseManager {
	mock := &MockreconcileUsecaseManager{ctrl: ctrl}
	mock.recorder = &MockreconcileUsecaseManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreconcileUsecaseManager) EXPECT() *MockreconcileUsecaseManagerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockreconcileUsecaseManager) Reconcile(ctx context.Context, request reconcile.ReconcileRequest) (reconcile.ReconcileSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, request)
	ret0, _ := ret[0].(reconcile.ReconcileSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockreconcileUsecaseManagerMockRecorder) Reconcile(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockreconcileUsecaseManager)(nil).Reconcile), ctx, request)
}

// ReconcileFromRecords mocks base method.
func (m *MockreconcileUsecaseManager) ReconcileFromRecords(ctx context.Context, sysTrx []reconcile.SystemTransaction, bankStmts []reconcile.BankStatement, start, end time.Time) (reconcile.ReconcileSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileFromRecords", ctx, sysTrx, bankStmts, start, end)
	ret0, _ := ret[0].(reconcile.ReconcileSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileFromRecords indicates an expected call of ReconcileFromRecords.
func (mr *MockreconcileUsecaseManagerMockRecorder) ReconcileFromRecords(ctx, sysTrx, bankStmts, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileFromRecords", reflect.TypeOf((*MockreconcileUsecaseManager)(nil).ReconcileFromRecords), ctx, sysTrx, bankStmts, start, end)
}

// MockinfraProvider is a mock of infraProvider interface.
type MockinfraProvider struct {
	ctrl     *gomock.Controller
	recorder *MockinfraProviderMockRecorder
}

// MockinfraProviderMockRecorder is the mock recorder for MockinfraProvider.
type MockinfraProviderMockRecorder struct {
	mock *MockinfraProvider
}

// NewMockinfraProvider creates a new mock instance.
func NewMockinfraProvider(ctrl *gomock.Controller) *MockinfraProvider {
	mock := &MockinfraProvider{ctrl: ctrl}
	mock.recorder = &MockinfraProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinfraProvider) EXPECT() *MockinfraProviderMockRecorder {
	return m.recorder
}

// CsvNewReader mocks base method.
func (m *MockinfraProvider) CsvNewReader(r io.Reader) *csv.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CsvNewReader", r)
	ret0, _ := ret[0].(*csv.Reader)
	return ret0
}

// CsvNewReader indicates an expected call of CsvNewReader.
func (mr *MockinfraProviderMockRecorder) CsvNewReader(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CsvNewReader", reflect.TypeOf((*MockinfraProvider)(nil).CsvNewReader), r)
}

// CsvReadAll mocks base method.
func (m *MockinfraProvider) CsvReadAll(r gocsv.Reader) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CsvReadAll", r)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CsvReadAll indicates an expected call of CsvReadAll.
func (mr *MockinfraProviderMockRecorder) CsvReadAll(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CsvReadAll", reflect.TypeOf((*MockinfraProvider)(nil).CsvReadAll), r)
}

// TimeInRange mocks base method.
func (m *MockinfraProvider) TimeInRange(d, start, end time.Time) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeInRange", d, start, end)
	ret0, _ := ret[0].(bool)
	return ret0
}

// TimeInRange indicates an expected call of TimeInRange.
func (mr *MockinfraProviderMockRecorder) TimeInRange(d, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeInRange", reflect.TypeOf((*MockinfraProvider)(nil).TimeInRange), d, start, end)
}
