// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package reconcile is a generated GoMock package.
package reconcile

import (
	context "context"
	reflect "reflect"

	reconcile "github.com/ferdianexe/simple-statement-reconciliation/internal/usecase/reconcile"
	gomock "github.com/golang/mock/gomock"
)

// MockreconcileUsecaseManager is a mock of reconcileUsecaseManager interface.
type MockreconcileUsecaseManager struct {
	ctrl     *gomock.Controller
	recorder *MockreconcileUsecaseManagerMockRecorder
}

// MockreconcileUsecaseManagerMockRecorder is the mock recorder for MockreconcileUsecaseManager.
type MockreconcileUsecaseManagerMockRecorder struct {
	mock *MockreconcileUsecaseManager
}

// NewMockreconcileUsecaseManager creates a new mock instance.
func NewMockreconcileUsecaseManager(ctrl *gomock.Controller) *MockreconcileUsecaseManager {
	mock := &MockreconcileUsecaseManager{ctrl: ctrl}
	mock.recorder = &MockreconcileUsecaseManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreconcileUsecaseManager) EXPECT() *MockreconcileUsecaseManagerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockreconcileUsecaseManager) Reconcile(ctx context.Context, request reconcile.ReconcileRequest) (reconcile.ReconcileSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, request)
	ret0, _ := ret[0].(reconcile.ReconcileSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockreconcileUsecaseManagerMockRecorder) Reconcile(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockreconcileUsecaseManager)(nil).Reconcile), ctx, request)
}
